version: '3.8'

x-defaults: &default
  network: &network
    networks:
      - net

services:
  php:
    build: ./docker
    ports:
      - 88:80
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # entrypoint: /usr/local/bin/entrypoint.sh
    <<: *network

  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/imports:/var/lib/mysql-files
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=lorem_news
      - MYSQL_USER=LoremNews
      - MYSQL_PASSWORD=NewsLorem
      - MYSQL_ALLOW_LOCAL_INFILE=true
    <<: *network

  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - "db"
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=30M
    ports:
      - "89:80"
    <<: *network

networks:
  net:
  